# Assignment - 1

In [1]:
import torch
import numpy as np
import torch.nn as nn
import torch.optim as optim
import tensorflow as tf
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import r2_score, mean_squared_error

np.random.seed(42)

## 1. Introduction of PyTorch Tensors and Basic Operations

### a. PyTorch Tensors, Initialization Methods, and Data Types

In [2]:
a = torch.tensor([1, 2, 3], dtype=torch.float32)
b = torch.zeros((2, 3))
c = torch.ones((3, 3))
d = torch.rand((2, 2))
e = torch.arange(0, 10, 2)

print(a, a.dtype)
print(b)
print(c)
print(d)
print(e)

tensor([1., 2., 3.]) torch.float32
tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
tensor([[0.2875, 0.5558],
        [0.3879, 0.8983]])
tensor([0, 2, 4, 6, 8])


### b. Tensor Operations: Arithmetic, Broadcasting, Indexing, and Reshaping

In [3]:
x = torch.tensor([[1, 2], [3, 4]])
y = torch.tensor([[5, 6], [7, 8]])

print(x + y)
print(x * y)

print(x + 10)

print(x[0])
print(x[:, 1])

z = torch.arange(1, 9)
print(z.reshape(2, 4))

tensor([[ 6,  8],
        [10, 12]])
tensor([[ 5, 12],
        [21, 32]])
tensor([[11, 12],
        [13, 14]])
tensor([1, 2])
tensor([2, 4])
tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])


### c. Automatic Differentiation using PyTorch’s Autograd System

In [4]:
x = torch.tensor(2.0, requires_grad=True)
y = x ** 3 + 2 * x

y.backward()
print("Gradient dy/dx:", x.grad)

Gradient dy/dx: tensor(14.)


## 2. Linear Algebra Operations with TensorFlow

In [5]:
A = tf.constant([[1., 2.], [3., 4.]])
B = tf.constant([[5., 6.], [7., 8.]])

print("Addition:\n", tf.add(A, B))
print("Multiplication:\n", tf.matmul(A, B))
print("Transpose:\n", tf.transpose(A))
print("Determinant:", tf.linalg.det(A))
print("Inverse:\n", tf.linalg.inv(A))
print("Eigenvalues:", tf.linalg.eig(A))

Addition:
 tf.Tensor(
[[ 6.  8.]
 [10. 12.]], shape=(2, 2), dtype=float32)
Multiplication:
 tf.Tensor(
[[19. 22.]
 [43. 50.]], shape=(2, 2), dtype=float32)
Transpose:
 tf.Tensor(
[[1. 3.]
 [2. 4.]], shape=(2, 2), dtype=float32)
Determinant: tf.Tensor(-2.0, shape=(), dtype=float32)
Inverse:
 tf.Tensor(
[[-2.0000002   1.0000001 ]
 [ 1.5000001  -0.50000006]], shape=(2, 2), dtype=float32)
Eigenvalues: (<tf.Tensor: shape=(2,), dtype=complex64, numpy=array([-0.37228122+0.j,  5.372281  +0.j], dtype=complex64)>, <tf.Tensor: shape=(2, 2), dtype=complex64, numpy=
array([[-0.8245648 +0.j, -0.41597357+0.j],
       [ 0.56576747+0.j, -0.90937674+0.j]], dtype=complex64)>)


## 3. AND & OR Gates using Perceptron

In [6]:
def perceptron(x, w, b):
    return 1 if np.dot(x, w) + b >= 0 else 0

X = np.array([[0,0], [0,1], [1,0], [1,1]])

w_and = np.array([1, 1])
b_and = -1.5
print("AND Gate:")
for x in X:
    print(x, perceptron(x, w_and, b_and))

w_or = np.array([1, 1])
b_or = -0.5
print("\nOR Gate:")
for x in X:
    print(x, perceptron(x, w_or, b_or))

AND Gate:
[0 0] 0
[0 1] 0
[1 0] 0
[1 1] 1

OR Gate:
[0 0] 0
[0 1] 1
[1 0] 1
[1 1] 1


## 4. XOR Problem using PyTorch Neural Network

In [7]:
X = torch.tensor([[0.,0.], [0.,1.], [1.,0.], [1.,1.]])
Y = torch.tensor([[0.], [1.], [1.], [0.]])

model = nn.Sequential(
    nn.Linear(2, 4),
    nn.ReLU(),
    nn.Linear(4, 1),
    nn.Sigmoid()
)

criterion = nn.BCELoss()
optimizer = optim.Adam(model.parameters(), lr=0.1)

for epoch in range(2000):
    optimizer.zero_grad()
    output = model(X)
    loss = criterion(output, Y)
    loss.backward()
    optimizer.step()

print("XOR Output:")
print(model(X).round())

XOR Output:
tensor([[0.],
        [1.],
        [1.],
        [0.]], grad_fn=<RoundBackward0>)


## 5. Simple Neural Network to Solve Regression Problem

![Neural Network](Neural_Network.png)

In [8]:
data = pd.read_csv("Data.csv")
X = data.iloc[:, :-1].values
y = data.iloc[:, -1].values.reshape(-1,1)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [9]:
x_scaler = StandardScaler()
y_scaler = StandardScaler()

X_train = x_scaler.fit_transform(X_train)
X_test = x_scaler.transform(X_test)

y_train = y_scaler.fit_transform(y_train)
y_test = y_scaler.transform(y_test)

In [10]:
def sigmoid(x):
    x = np.clip(x, -500, 500)
    return 1/(1+np.exp(-x))

def sigmoid_derivative(x):
    return x*(1-x)

In [11]:
input_size = X_train.shape[1]
hidden_size = 4
output_size = 1

np.random.seed(42)

W1 = np.random.randn(input_size, hidden_size) * 0.1
b1 = np.zeros((1, hidden_size))

W2 = np.random.randn(hidden_size, output_size) * 0.1
b2 = np.zeros((1, output_size))

learning_rate = 0.001
epochs = 10000

In [12]:
for epoch in range(epochs):
    z1 = np.dot(X_train, W1) + b1
    a1 = sigmoid(z1)

    z2 = np.dot(a1, W2) + b2
    y_pred = z2

    d_loss = 2*(y_pred - y_train)/y_train.shape[0]

    dW2 = np.dot(a1.T, d_loss)
    db2 = np.sum(d_loss, axis=0)

    da1 = np.dot(d_loss, W2.T)
    dz1 = da1 * sigmoid_derivative(a1)

    dW1 = np.dot(X_train.T, dz1)
    db1 = np.sum(dz1, axis=0)

    W2 -= learning_rate*dW2
    b2 -= learning_rate*db2
    W1 -= learning_rate*dW1
    b1 -= learning_rate*db1

In [13]:
z1 = np.dot(X_test, W1) + b1
a1 = sigmoid(z1)
z2 = np.dot(a1, W2) + b2
y_pred_test = z2

y_pred_test = y_scaler.inverse_transform(y_pred_test)
y_test = y_scaler.inverse_transform(y_test)

In [14]:
r2 = r2_score(y_test, y_pred_test)
rmse = np.sqrt(mean_squared_error(y_test, y_pred_test))

print("R2 Score:", r2)
print("RMSE:", rmse)

R2 Score: 0.20141033306054812
RMSE: 209488.49366140185
