In [1]:
import torch
import numpy as np
import torch.nn as nn
import torch.optim as optim
# import tensorflow as tf

# Q1

In [2]:
a = torch.tensor([1, 2, 3], dtype=torch.float32)
b = torch.zeros((2, 3))
c = torch.ones((3, 3))
d = torch.rand((2, 2))
e = torch.arange(0, 10, 2)

print(a, a.dtype)
print(b)
print(c)
print(d)
print(e)

tensor([1., 2., 3.]) torch.float32
tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
tensor([[0.7036, 0.5613],
        [0.6570, 0.6904]])
tensor([0, 2, 4, 6, 8])


In [3]:
x = torch.tensor([[1, 2], [3, 4]])
y = torch.tensor([[5, 6], [7, 8]])

print(x + y)
print(x * y)

print(x + 10)

print(x[0])
print(x[:, 1])

z = torch.arange(1, 9)
print(z.reshape(2, 4))

tensor([[ 6,  8],
        [10, 12]])
tensor([[ 5, 12],
        [21, 32]])
tensor([[11, 12],
        [13, 14]])
tensor([1, 2])
tensor([2, 4])
tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])


In [4]:
x = torch.tensor(2.0, requires_grad=True)
y = x ** 3 + 2 * x

y.backward()
print("Gradient dy/dx:", x.grad)

Gradient dy/dx: tensor(14.)


# Q2

In [5]:
# A = tf.constant([[1., 2.], [3., 4.]])
# B = tf.constant([[5., 6.], [7., 8.]])

# print("Addition:\n", tf.add(A, B))
# print("Multiplication:\n", tf.matmul(A, B))
# print("Transpose:\n", tf.transpose(A))
# print("Determinant:", tf.linalg.det(A))
# print("Inverse:\n", tf.linalg.inv(A))
# print("Eigenvalues:", tf.linalg.eig(A))

# Q3

In [6]:
def perceptron(x, w, b):
    return 1 if np.dot(x, w) + b >= 0 else 0

X = np.array([[0,0], [0,1], [1,0], [1,1]])

w_and = np.array([1, 1])
b_and = -1.5
print("AND Gate:")
for x in X:
    print(x, perceptron(x, w_and, b_and))

w_or = np.array([1, 1])
b_or = -0.5
print("\nOR Gate:")
for x in X:
    print(x, perceptron(x, w_or, b_or))

AND Gate:
[0 0] 0
[0 1] 0
[1 0] 0
[1 1] 1

OR Gate:
[0 0] 0
[0 1] 1
[1 0] 1
[1 1] 1


# Q4

In [7]:
X = torch.tensor([[0.,0.], [0.,1.], [1.,0.], [1.,1.]])
Y = torch.tensor([[0.], [1.], [1.], [0.]])

model = nn.Sequential(
    nn.Linear(2, 4),
    nn.ReLU(),
    nn.Linear(4, 1),
    nn.Sigmoid()
)

criterion = nn.BCELoss()
optimizer = optim.Adam(model.parameters(), lr=0.1)

for epoch in range(2000):
    optimizer.zero_grad()
    output = model(X)
    loss = criterion(output, Y)
    loss.backward()
    optimizer.step()

print("XOR Output:")
print(model(X).round())

XOR Output:
tensor([[0.],
        [1.],
        [1.],
        [0.]], grad_fn=<RoundBackward0>)


# Q5

In [8]:
X = torch.unsqueeze(torch.linspace(0, 10, 100), dim=1)
Y = 2 * X + 1

model = nn.Sequential(
    nn.Linear(1, 10),
    nn.ReLU(),
    nn.Linear(10, 1)
)

criterion = nn.MSELoss()
optimizer = optim.Adam(model.parameters(), lr=0.01)

for epoch in range(1000):
    optimizer.zero_grad()
    predictions = model(X)
    loss = criterion(predictions, Y)
    loss.backward()
    optimizer.step()

print("Final Loss:", loss.item())

Final Loss: 8.157935553754214e-07
